import { VideoType } from './Entities/type';

export const filmInformation: VideoType[] = [
	{
		id: '1',
		title: 'Boruto : The next generations',
		channel: 'ABC channel',
		description:
			'As peace prevails throughout the ninja clans, so does the question of becoming one. Now a generation of prodigy like Boruto Uzumaki, son of Seventh Hokage Naruto Uzumaki, are challenged living under their parents’ shadow. The shinobi life has changed and so must the path to it. The legacy of ninja continues and a new chapter of ninja begins!',
		url: 'Qyonn5Vbg7s',
		like: [],
		dislike: [],
		tags: ['anime'],
		category: 'anime',
		totalViews: 15,
		createdAt: new Date(),
		updateAt: new Date(),
	},
	{
		id: '2',
		title: 'Banpresto World Figure Colosseum',
		channel: 'ABC channel',
		description:
			'The Banpresto World Figure Colosseum pits 12 of the world`s best sculptors against each other to see who can sculpt the ultimate Dragon Ball Z and One Piece figures. Witness the birth of Banpresto`s next generation of toys before they hit the shelves.',
		url: 'YEDSmnbuhvE',
		like: [],
		dislike: [],
		tags: ['anime'],
		category: 'anime',
		totalViews: 16,
		createdAt: new Date(),
		updateAt: new Date(),
	},
	{
		id: '3',
		title: 'Folktales from Japan',
		channel: 'ABC channel',
		description:
			'Like in any culture, Japanese kids grow up listening to the stories repeatedly told by their parents and grandparents. The boy born from a peach; the princess from the moon who is discovered inside a bamboo; the old man who can make a dead cherry tree blossom, etc. These short stories that teach kids to see both the dark and bright sides of life have passed traditional moral values from generation to generation.',
		url: 'AlqbHoBH3Lg',
		like: [],
		dislike: [],
		tags: ['anime'],
		category: 'anime',
		totalViews: 5,
		createdAt: new Date(),
		updateAt: new Date(),
	},
	{
		id: '4',
		title: 'Guyver: The Bioboosted Armor',
		channel: 'ABC channel',
		description:
			'While investigating a mysterious explosion, Sho Fukamachi discovers the Chronos Corporation`s greatest weapon: a techno-organic suit of bio-armor known as the Guyver. With Chronos determined to conceal its secrets, Sho finds himself relentlessly pursued by an army of horrific bio-monsters. When he runs out of options, Sho is forced to call upon the fearsome powers of the Guyver.',
		url: '0poOZLGfl9s',
		like: [],
		dislike: [],
		tags: ['anime'],
		category: 'anime',
		totalViews: 1034,
		createdAt: new Date(),
		updateAt: new Date(),
	},
	{
		id: '5',
		title: 'CARDFIGHT!! VANGUARD overDress',
		channel: 'ABC channel',
		description:
			'Third-year middle school student Yu-yu Kondo lives in Kanazawa city of the country of Kaga. Being unable to reject requests, Yu-yu often gets caught up in his sister`s hobbies. When Yu-yu could no longer bear it and ran away from home, he was saved by Megumi Okura. Megumi invites Yu-yu to the Night Amusement Park "Wonder Hill" where her friends gather. The amusement park is where many youths of the Vanguard-centric group "Team Blackout" gather. And this is how Yu-yu encounters Vanguard and was drawn in by the appeal of Vanguard and the world and friends he had never seen before.',
		url: '7kOKATFY2ck',
		like: [],
		dislike: [],
		tags: ['anime'],
		category: 'anime',
		totalViews: 2386,
		createdAt: new Date(),
		updateAt: new Date(),
	},
	{
		id: '6',
		title: 'Disgaea',
		channel: 'ABC channel',
		description:
			'Laharl, the demon prince of the Netherworld and son of the late Lord Krichevskoy, is awakened by Flonne, the sugary-sweet angel-in-training sent to assassinate the overlord. Etna, the Prinnies, and Flonne, join the selfish, disgruntled, and perpetually hungry Laharl as he treks the deepest, darkest realms to become king of the cursed land.',
		url: 'ZqTtsErHJ-c',
		like: [],
		dislike: [],
		tags: ['anime'],
		category: 'anime',
		totalViews: 324,
		createdAt: new Date(),
		updateAt: new Date(),
	},
];
